### ISSUE TITLE
Links in Admonitions are not displayed in Graph View

### ISSUE THREAD

**Issue by TobiasKlosek** [valentine195/obsidian-admonition#18]
Somehow the Links which are located inside the Blocks are being ignored:
At the right is the Local-Graph-View.
![image](https://user-images.githubusercontent.com/61796661/116533566-cf106c00-a8e1-11eb-8d66-8bd7d7226c8f.png)

Here i created the link outside the Codeblock and as you can see it works properly.

![image](https://user-images.githubusercontent.com/61796661/116533652-ec453a80-a8e1-11eb-9583-3969013f3703.png)

**Comment by TobiasKlosek** [comment]
I dont know how much influence this Plugin can have, but a (quite ugly) but simple Workaround would be, to search for links inside these blocks and inserting the matches right after the block inside these: `%% [[LINK]] %%`:
![image](https://user-images.githubusercontent.com/61796661/116536383-206e2a80-a8e5-11eb-9d98-346d912f8aae.png)

**Comment by valentine195** [comment]
Unfortunately this would be difficult to solve. I don't know how Obsidian's graph view is created, but I would assume it is being built from their metadata cache. Because the Admonition content is rendered as markdown _after_ the note, it is not pushed into the cache.

I think if you require the graph view to show this, you'll have to create the links outside of the admonitions (at least for now -- I'll try to think of a way to possibly implement this, or the API could be updated to allow for it easier).

**Comment by TobiasKlosek** [comment]
I already thought about that this is on Obsidians site. They're probably ignoring everything whats inside these codeblocks.
Thanks btw for these fast responses and implementations! Really appreciate it.

**Comment by TobiasKlosek** [comment]
Do you see any chances to accomplish that? It's very unfortunate to write the links again outside the blocks... since this is the last thing that somehow hinders me to fully migrate on using these admonitions

**Comment by valentine195** [comment]
Thanks for opening the feature request. Like I said, I have no idea how the graph view plugin works, and even my guess about data not being pushed into the cache could be incorrect. If there's any suggestions in that thread I'll implement it ASAP.

**Comment by valentine195** [comment]
Possibly. In adding support for nested admonitions, I basically programmed support for the Python syntax (`!!! ad-note`) anyway. I'll tinker with allowing it at the top level instead of a code block, but you won't get the background highlighting (unless I can figure out how to add some new syntax to the CodeMirror editor).

**Comment by TobiasKlosek** [comment]
That would be awesome! I can wait for the background highlighting, but getting the Links automatically generated by Obsidian would be awesome!

**Comment by valentine195** [comment]
Something like this:

![image](https://user-images.githubusercontent.com/38669521/117181709-87875580-ada3-11eb-99b2-e5f17f0cb507.png)

**Comment by TobiasKlosek** [comment]
Gotcha. Ok for now that will be sufficient I think. This was/is kinda nice because it also provides a visual breakdown of the different sections. Thanks for being so fast!

**Comment by valentine195** [comment]
This is a rather difficult problem, unfortunately. I can't give you a timeline.

**Comment by TobiasKlosek** [comment]
Oh, sorry to hear that.. but thanks for hearing me.

**Comment by TobiasKlosek** [comment]
hey, is there any chance to get the backlinks somehow working? I already wrote with a bunch of people looking for an alternative way to get the backlinks working outside your admonition plugin but unfortunately with no success..

**Comment by valentine195** [comment]
## 4.3.0

Please see [this new setting](https://github.com/valentine195/obsidian-admonition#sync-links-to-metadata-cache).

**Comment by TobiasKlosek** [comment]
Thanks! This made my day! :)
