### ISSUE TITLE
Compatibility with the plugin Table Extended ? 

### ISSUE THREAD

**Issue by I-Pch** [valentine195/obsidian-admonition#188]
Hi there 😊 !

So I know Admonition support markdown tables (at least, in Live Preview, tables are kind of rendered as tables without borders 😊 and the tables get fully rendered in Reading mode ) ... 

Would it be possible to make Admonition compatible with [Table Extended](https://github.com/aidenlx/table-extended) so we could create/use MultiMarkdown tables within admonitions ? 😇  

As far as I can see it, the MultiMarkdown Tables are not that different from a conventional markdown table but to work with the Table Extended plugin, a `-tx-` needs to be prepend to the table (instead of a potentially new line and a potentially empty header )
 
... I'm not a dev' so I have no idea if it would be feasible and how much work this would represent (sorry 😔 ) but I had to ask 😇 ...
If it's not doable, that's not a problem either 😇 ...

As I didn't know who I should contact for this, I also opened an issue about this in the [Table Extended repo](https://github.com/aidenlx/table-extended/issues/35#issue-1144678337) 😇 .

**Comment by valentine195** [comment]
Obsidian has added callouts to the latest insider build that do not have the post processor sequencing issues of the Admonitions plugin since they are tightly integrated into Obsidian's internals.

If you need to use other plugins inside callouts, I recommend using them when it is released to the public.
