### ISSUE TITLE
Speeding up Metadatacache and creating non-existing links

### ISSUE THREAD

**Issue by TobiasKlosek** [valentine195/obsidian-admonition#36]
Hello,

I found some possible enhancement to the new metadata-feature.

- It seems somehow laggy when creating Links and looking if they are created in the graph view (and sometimes dont even are created) 
- non-existing links wont be created

**Comment by valentine195** [comment]
> It seems somehow laggy when creating Links and looking if they are created in the graph view (and sometimes dont even are created)

I realize that the graph view updates "live" in edit mode, but I do not believe it will be possible for me to do that.

As far as not being created - this functionality is _not_ something that is supported by Obsidian, and anything that causes Obsidian to re-resolve the file could remove the links from the graph view. I'll work on making it more stable, but there's a real possibility that this is the best we'll be able to do for this feature.

> non-existing links wont be created

Fixed in 4.3.1

**Comment by TobiasKlosek** [comment]
Ok I understand. Obsidian should fully support backlinks inside codeblocks, maybe they take a look at it after the mobile release is done.

I see that after restarting obsidian the outgoing links of that note aren't created. Is there a way to create a shortcut for writing the metadata-cache manually? So that after opening obsidian or editing the file, running the update metadatacache command would update the graph view?

**Comment by TobiasKlosek** [comment]
Ah i understand, but wouldnt it be possible to avoid artifacts if there would be a way to manually (via hotkeys for e.g) write the plugin-data?

**Comment by valentine195** [comment]
The plugin would still need to store that data to write it, which means it would need to update it when files are changed/removed/added.

**Comment by valentine195** [comment]
@TobiasKlosek, I'm going to leave this open because it is referring to the "Sync Links" functionality, but I just released version 6.0.0 that allows you to create non-code block Admonitions. See [here](https://github.com/valentine195/obsidian-admonition#non-code-block-admonitions) for more information.

**Comment by TobiasKlosek** [comment]
@valentine195 thanks! That is nice! I just found one more thing to correct. I will create a FR.

**Comment by MatteCrystal** [comment]
This "Sync Links" functionality would be exceptionally useful to me. If you can get it working with the basic code blocks that would be ideal. But if the non-code block Admonitions gets to the point where they're 100% as functional as the code block method then that would be great too. 

ATM lack of styling options and nesting makes the current iteration of non-code-block Admonitions not useable for my current use case.

Also, non-code-block Admonitions don't seem to support HTML for the title like the code block version does. 
![image](https://user-images.githubusercontent.com/32424764/136671755-c036ea5d-db10-41c3-b9fa-bb296c85d132.png)
That gold line is due to me using `<div class="pageTitle small">Navigation</div>` as the title text. doing this with the non-code-block version causes errors.

**Comment by MatteCrystal** [comment]
Also if by chance you figure out a way to Sync Links for the code block style Admonitions. The ability to have that synced links be togglable could be useful. For example, if you look at the image in my last post. I would want links in parents to be synced but the list of links under children I would want to keep unsynced, regardless of if I've visited the page or not.

**Comment by valentine195** [comment]
Grouped into master issue.
