### ISSUE TITLE
Mermaid doesn't render when Admonition block has collapse

### ISSUE THREAD

**Issue by ConnorMeyers** [valentine195/obsidian-admonition#72]
Admonition blocks with an enclosed mermaid graph as well as the collapse modifier (when not set to open), causes the mermaid graph's rendering to fail:
![image](https://user-images.githubusercontent.com/14039575/128735995-24bcac5b-2bb5-40c7-aa51-adfc79209b46.png)

`````
````ad-note
collapse: closed
```mermaid
graph LR
    A --> B
```
````
`````

**Comment by valentine195** [comment]
Seems like this is due to an upstream bug from mermaid. If the element it is being added to does not have any dimensions, the generated graph will also not have any dimensions.

Unfortunately for me, this means I have to show the element as open for a split second before collapsing it, but it works in 6.2.5 now.
